theme: jekyll-theme-cayman
title: 3rd International Workshop on Empirical Methods in Conceptual Modeling (EmpER’20) co-located at ER 2020
plugins:
  - jekyll-relative-links
  - jekyll-redirect-from
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
